// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOEMOARo3E4lZPs3i9xnoElvzAUydHkT8',
    appId: '1:1083611783454:web:ef2e19d22a0770037fe90f',
    messagingSenderId: '1083611783454',
    projectId: 'goodbooks-flutter',
    authDomain: 'goodbooks-flutter.firebaseapp.com',
    storageBucket: 'goodbooks-flutter.firebasestorage.app',
    measurementId: 'G-40CFWY4C1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXdKZOrSNOVR7MOPk2lObNKz1fx48MOE',
    appId: '1:1083611783454:android:f5e0a0f2fa98c5fc7fe90f',
    messagingSenderId: '1083611783454',
    projectId: 'goodbooks-flutter',
    storageBucket: 'goodbooks-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-BnY87nQGYotE8pmi9YS13hP5S4563I',
    appId: '1:1083611783454:ios:b2074919a0529e847fe90f',
    messagingSenderId: '1083611783454',
    projectId: 'goodbooks-flutter',
    storageBucket: 'goodbooks-flutter.firebasestorage.app',
    iosBundleId: 'com.example.goodbooksFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-BnY87nQGYotE8pmi9YS13hP5S4563I',
    appId: '1:1083611783454:ios:b2074919a0529e847fe90f',
    messagingSenderId: '1083611783454',
    projectId: 'goodbooks-flutter',
    storageBucket: 'goodbooks-flutter.firebasestorage.app',
    iosBundleId: 'com.example.goodbooksFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOEMOARo3E4lZPs3i9xnoElvzAUydHkT8',
    appId: '1:1083611783454:web:ffacee6ccfc661d17fe90f',
    messagingSenderId: '1083611783454',
    projectId: 'goodbooks-flutter',
    authDomain: 'goodbooks-flutter.firebaseapp.com',
    storageBucket: 'goodbooks-flutter.firebasestorage.app',
    measurementId: 'G-BTN8XYKXBQ',
  );
}
